name: ulmo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
# To see which dependencies have newer versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # ---------- Firebase ----------
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  firebase_analytics: ^10.7.4
  firebase_messaging: ^14.7.9
  firebase_crashlytics: ^3.4.8

  # ---------- State Management (BLoC) ----------
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  # ---------- Dependency Injection ----------
  get_it: ^7.6.0

  # ---------- Network & API ----------
  dio: ^5.3.0
  http: ^1.1.0
  connectivity_plus: ^5.0.2

  # ---------- Local Storage ----------
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0  # For securely storing sensitive data

  # ---------- UI & Widgets ----------
  curved_navigation_bar: ^1.0.3
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  animated_splash_screen: ^1.3.0
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.2
  google_places_flutter: ^2.0.6
  dotted_border: ^2.0.0+3
  google_maps_flutter: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  pull_to_refresh: ^2.0.0
  lottie: ^2.7.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  photo_view: ^0.14.0
  flutter_screenutil: ^5.9.0  # For responsive UI across different screen sizes
  flutter_staggered_animations: ^1.1.1  # For animation collections

  # ---------- Utilities ----------
  flutter_native_splash: ^2.3.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  intl: ^0.18.1
  uuid: ^3.0.7
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  permission_handler: ^11.0.1
  logger: ^2.0.2+1  # Better logging
  timeago: ^3.6.0


  # ---------- E-Commerce Specific ----------
  flutter_stripe: ^9.5.0+1
  barcode_scan2: ^4.2.4
  flutter_paypal: ^0.2.0  # For PayPal integration
  qr_flutter: ^4.1.0  # For generating QR codes
  rxdart: ^0.27.7  # Reactive programming extensions
  google_sign_in: ^6.3.0
  otp_text_field: ^1.1.3
  otp_text_field_v2: ^1.0.3
  flutter_otp_text_field: ^1.5.1+1
  loading_indicator: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

